spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/sara0818/JavaEE-SpringCloud-Bus.git
  rabbitmq:
    host: 192.168.246.134
eureka:
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
